/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author evada
 */
public class NewJFrame extends javax.swing.JFrame {
    private int[] tentative = new int[4];
    private int essais = 0;
    private final int maxEssais = 10;
    Combinaisons combinaisonSecrete = new Combinaisons();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        bouton_valide = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("texte_intro");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 37, -1));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

                        texte_chiffre_0.setText("0");
                        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

                        texte_chiffre_1.setText("0");
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

                        texte_chiffre_2.setText("0");
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

                        texte_chiffre_3.setText("0");
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

                        texte_lbl_nb_chiffres_exacts.setText("texte_lbl_nb_chiffres_exacts");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

                        texte_nb_chiffres_exacts.setText("texte_nb_chiffres_exacts");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

                        texte_lbl_nb_chiffres_haut.setText("texte_lbl_nb_chiffres_haut");
                        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

                        texte_nb_chiffres_haut.setText("texte_nb_chiffres_haut");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

                        texte_lbl_nb_chiffres_bas.setText("texte_lbl_nb_chiffres_bas");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

                        texte_nb_chiffres_bas.setText("texte_nb_chiffres_bas");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

                        texte_score.setText("texte_score");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

                        texte_tentatives.setText("texte_tentatives");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

                        bouton_recommencer.setText("jButton1");
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

                        bouton_valide.setText("Validé");
                        bouton_valide.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_valideActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_valide, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents
    
    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        // TODO add your handling code here:
        int value = Integer.parseInt(texte_chiffre_0.getText());
        if (value > 0) {
           
            texte_chiffre_0.setText(String.valueOf(value - 1));
            
        }

    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
        int value = Integer.parseInt(texte_chiffre_0.getText());
        if (value < 9) {
            
            texte_chiffre_0.setText(String.valueOf(value + 1));
            
        }
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
        int value = Integer.parseInt(texte_chiffre_1.getText());
        if (value < 9) {
           
            texte_chiffre_1.setText(String.valueOf(value + 1));
            
        }
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        // TODO add your handling code here:
        int value = Integer.parseInt(texte_chiffre_2.getText());
        if (value < 9) {
            
            texte_chiffre_2.setText(String.valueOf(value + 1));
            
        }
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        // TODO add your handling code here:
        int value = Integer.parseInt(texte_chiffre_3.getText());
        if (value < 9) {
            
            texte_chiffre_3.setText(String.valueOf(value + 1));
            
        }
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        // TODO add your handling code here:
        int value = Integer.parseInt(texte_chiffre_1.getText());
        if (value > 0) {
            
            texte_chiffre_1.setText(String.valueOf(value - 1));
            
        }
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        // TODO add your handling code here:
        int value = Integer.parseInt(texte_chiffre_2.getText());
        if (value > 0) {
            
            texte_chiffre_2.setText(String.valueOf(value - 1));
            
        }
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        // TODO add your handling code here:
        int value = Integer.parseInt(texte_chiffre_3.getText());
        if (value > 0) {
            
            texte_chiffre_3.setText(String.valueOf(value - 1));
            
        }
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_valideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_valideActionPerformed
        // TODO add your handling code here:
        int[] code = combinaisonSecrete.getChiffres();
        
        int score = 0;
        essais++;


        StringBuilder monter = new StringBuilder();
        StringBuilder descendre = new StringBuilder();
        StringBuilder exact = new StringBuilder();
       
        tentative[0] = Integer.parseInt(texte_chiffre_0.getText());
        tentative[1] = Integer.parseInt(texte_chiffre_1.getText());
        tentative[2] = Integer.parseInt(texte_chiffre_2.getText());
        tentative[3] = Integer.parseInt(texte_chiffre_3.getText());
       


        for (int i = 0; i < code.length; i++) {
            if (tentative[i] < code[i]) {
                monter.append("C").append(i+1).append(" ");
            } else if (tentative[i] > code[i]) {
                descendre.append("C").append(i+1).append(" ");
            } else {
                exact.append("C").append(i+1).append(" ");
            }
        }
        if (combinaisonSecrete.verifier(tentative)) {
            texte_tentatives.setText("Tentative :" + essais + " / " + maxEssais);
            bouton_valide.setEnabled(false);
            score += 1;
            texte_score.setText("Score :" +score);
        } else if (essais >= maxEssais) {
            texte_tentatives.setText("Tentative :" + essais + " / " + maxEssais);
            bouton_valide.setEnabled(false);
            score += 0;
            texte_score.setText(String.valueOf("Score :" +score));
            
        } else {
            texte_tentatives.setText("Tentative :" + essais + " / " + maxEssais);
            
        }




        texte_lbl_nb_chiffres_haut.setText("A monter :");
        texte_lbl_nb_chiffres_bas.setText("A descendre :");
        texte_lbl_nb_chiffres_exacts.setText("Chiffres exacts :");
        texte_nb_chiffres_haut.setText(monter.toString());
        texte_nb_chiffres_bas.setText(descendre.toString());
        texte_nb_chiffres_exacts.setText(exact.toString());
        
       
        
    
    }//GEN-LAST:event_bouton_valideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_valide;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
