/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author evada
 */
import javax.swing.SwingUtilities;
import java.awt.Color;


public class page_accueil extends javax.swing.JFrame {

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(page_accueil.class.getName());
    

         

    /**
     * Creates new form page_accueil
     */
    public page_accueil() {
        initComponents();
        getContentPane().setBackground(Color.PINK);
        setSize(600, 300);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bouton_commencer = new javax.swing.JButton();
        texte_intro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bouton_commencer.setText("COMMENCER");
        bouton_commencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_commencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_commencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        texte_intro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        texte_intro.setText("<html>Vous allez devoir trouvez une combinaison de 4 chiffres. Pour cela vous aurez 10 tentatives...  je vous conseille de vous aider des indices.</html>");
        texte_intro.setToolTipText("");
        texte_intro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 380, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_commencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_commencerActionPerformed
        // TODO add your handling code here:
        new NewJFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_bouton_commencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new page_accueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_commencer;
    private javax.swing.JLabel texte_intro;
    // End of variables declaration//GEN-END:variables
}
